name: CI
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "rockcraft.yaml"
      - ".github/workflows/**.yaml"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: canonical/identity-team/.github/workflows/_rock-build.yaml@2a4ae518f9c792dcdf14d05f8d86e3d72e160d96 # v1.9.0
    with:
      structure-tests-enabled: true
  gh-publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    uses: canonical/identity-team/.github/workflows/_rock-gh-publish.yaml@2a4ae518f9c792dcdf14d05f8d86e3d72e160d96 # v1.9.0
    with:
      rock: ${{ needs.build.outputs.rock }}
  oci-publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    uses: canonical/identity-team/.github/workflows/_rock-oci-publish.yaml@2a4ae518f9c792dcdf14d05f8d86e3d72e160d96 # v1.9.0
    with:
      edge-release: false
      eol-stable-release: "3 month"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  scan:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: gh-publish
    uses: canonical/identity-team/.github/workflows/_rock-scan.yaml@2a4ae518f9c792dcdf14d05f8d86e3d72e160d96 # v1.9.0
    with:
      image: ${{ needs.gh-publish.outputs.image }}
  oci-update-pr:
    needs: [gh-publish, scan]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: canonical/identity-team/.github/workflows/oci-update-pr.yaml@2a4ae518f9c792dcdf14d05f8d86e3d72e160d96 # v1.9.0
    with:
        oci-image: ${{ needs.gh-publish.outputs.image }}
        repository: canonical/oauth2-proxy-k8s-operator
    secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
